### ISSUE TITLE
Support HTTP/2 and new Notification API

### ISSUE THREAD

**Issue by mthuong** [KnuffApp/APNS-Pusher#32]
APNS Pusher seem not work when using new Apple Push Notification service SSL (Sandbox & Production).

Do we have any update to support https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html

Thanks

**Comment by QF-ZhouCheng** [comment]
i have the same issue, and the back-end re-write the push module, and show push successful, but the device still can not receive the notification.

**Comment by blommegard** [comment]
Thanks for the issue.

Didn't know they released the HTTP/2 support just yet. Will start looking in to it right away!

**Comment by blommegard** [comment]
@mthuong I assume you tried to use it in the production environment?

**Comment by blommegard** [comment]
Implemented in https://github.com/KnuffApp/APNS-Pusher/tree/develop now.
